services:
  - type: web
    name: morphed-tech-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: !Mahadev007!@gmail.com
      - key: ADMIN_PASSWORD
        value: !Mahakal007!@
      - key: UPI_ID
        value: morphedtech@paytm
      - key: UPI_NAME
        value: Morphed Tech
      - key: COURSE_PRICE
        value: 1111
      - key: NODE_ENV
        value: production
